### ISSUE TITLE
TVirtualStringTree do not publish `NodeDataSize` 

### ISSUE THREAD

**Issue by cdecu** [Virtual-TreeView/Virtual-TreeView#1240]
I have a small problem when compiling a application both as  x32 and as  x64  and storing Pointer in the node data.  
- At design time (in delphi) ,   NodeDataSize= 4 will be stored in the DFM.  
- When starting a x64, if **must be**  NodeDataSize= **8** but it read **4**. Causing a AV

So may be  , you could
- do not publish `NodeDataSize`  ?
- add a get default function to the published `NodeDataSize`  ? 

As a work around ,  I stop basing my custom treeview on the `TVirtualStringTree`   using `TCustomVirtualStringTree` instead.  
So I control the piublished properties  
Thanks

**Comment by joachimmarder** [comment]
Please respect our guidelines on the project homepage for submitting bugs. Please include your version of Virtual TreeView and Delphi, and attach a sample compiling project as ZIP to your report, or instructions how to modify one of the included sample projects to reproduce the problem. If only small changes are required, a description is sufficient how a demo projects needs to be changed in order to replicate the bug. If you already have a solution, please supply a patch file.

Please do not use the bug tracker for getting support, instead use [StackOverFlow](https://stackoverflow.com/).

Simply leave `NodeDataSize` on its default value -1, it will use the Pointer size automatically.

**Comment by cdecu** [comment]
Sorry, Thanks  for the reply
